### ISSUE TITLE
make presubmit issue: licensecheck typecheck validate_fuzzers_and_benchmarks Failed

### ISSUE THREAD

**Issue by syz913** [google/fuzzbench#1113]
Why do I get these issues? I just do as the getting-started say.
```bash
manul is not included in fuzzer list in /fuzzbench/.github/workflows/fuzzers.yml.
ERROR: validate_fuzzers_and_benchmarks failed, see errors above.
Failed checks: licensecheck typecheck validate_fuzzers_and_benchmarks
Failed.
make: *** [Makefile:60: presubmit] Error 1
```

**Comment by jonathanmetzman** [comment]
@syz913 did you make any changes to manul?
This check shouldn't have run on that fuzzer, so I'm a bit surprised.
@inferno-chromium I think the issue is that we removed a lot of fuzzers from CI in this [commit[(https://github.com/google/fuzzbench/commit/8a05393781845d171d01888b7bca0edbed22aeec#diff-f7784c9acea0c152e9ad76d92fcded79c342009768bc4d3800c8bd467318baedL24) but we check that every fuzzer modified is tested in CI [here](https://github.com/google/fuzzbench/blob/master/presubmit.py#L101). The options for fixing are 1. Test those fuzzers. 2. Don't do this validation. 3. Blocklist those fuzzers.

**Comment by inferno-chromium** [comment]
> @syz913 did you make any changes to manul?
> This check shouldn't have run on that fuzzer, so I'm a bit surprised.
> @inferno-chromium I think the issue is that we removed a lot of fuzzers from CI in this [commit](https://github.com/google/fuzzbench/commit/8a05393781845d171d01888b7bca0edbed22aeec#diff-f7784c9acea0c152e9ad76d92fcded79c342009768bc4d3800c8bd467318baedL24) but we check that every fuzzer modified is tested in CI [here](https://github.com/google/fuzzbench/blob/master/presubmit.py#L101). The options for fixing are 1. Test those fuzzers. 2. Don't do this validation. 3. Blocklist those fuzzers.

1. is expensive w.r.t CI.
I would say we do 2 or 3. 3 is better.

**Comment by inferno-chromium** [comment]
I looked again, you will see this error only if you modify that fuzzer. If you are modifying this fuzzer, we would want this to be tested in CI, so we would wait that fuzzer added back in https://github.com/google/fuzzbench/blob/master/.github/workflows/fuzzers.yml#L61

**Comment by syz913** [comment]
> I looked again, you will see this error only if you modify that fuzzer. If you are modifying this fuzzer, we would want this to be tested in CI, so we would wait that fuzzer added back in https://github.com/google/fuzzbench/blob/master/.github/workflows/fuzzers.yml#L61

thanks for your reply, I will try again
