### ISSUE TITLE
Error running FuzzBench with afl as the fuzzer and h2o Oss_fuzz project as the benchmark

### ISSUE THREAD

**Issue by mirzamomen** [google/fuzzbench#1198]
Hi. There is an issue running FuzzBench with afl as the fuzzer and h2o as the benchmark. I 've added h2o as the benchmark using the following command:

`PYTHONPATH=. python3 benchmarks/oss_fuzz_benchmark_integration.py -p h2o -f fuzz_target -c 49dc92128490d34aba00dfbde440979b9633ba14 -d 2021-07-06T06:35:23+09:00`

Then, I built it successfully running: 

`make build-afl-h2o_fuzz_target
`

However, when I run:

`make run-afl-h2o_fuzz_target
`

I receive the following error: 

`docker run \
--cpus=1 \
--cap-add SYS_NICE \
--cap-add SYS_PTRACE \
-e FUZZ_OUTSIDE_EXPERIMENT=1 \
-e FORCE_LOCAL=1 \
-e TRIAL_ID=1 \
-e FUZZER=afl \
-e BENCHMARK=h2o_fuzz_target \
-e FUZZ_TARGET=fuzz_target \
-it gcr.io/fuzzbench/runners/afl/h2o_fuzz_target
INFO:root:Doing trial as part of experiment.
INFO:root:Starting trial.
ERROR:root:Fuzz target binary not found.
INFO:root:Doing final sync.
--- Logging error ---
Traceback (most recent call last):
  File "/src/experiment/runner.py", line 374, in record_stats
    stats_json_str = fuzzer_module_get_stats(output_corpus,
  File "/src/fuzzers/afl/fuzzer.py", line 51, in get_stats
    with open(stats_file) as file_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/out/corpus/fuzzer_stats'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/experiment/runner.py", line 353, in do_sync
    self.record_stats()
  File "/src/experiment/runner.py", line 378, in record_stats
    logs.error('Call to %d failed.', fuzzer_module_get_stats)
  File "/src/common/logs.py", line 198, in error
    message % args)
TypeError: %d format: a number is required, not function

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Call stack:
  File "/src/experiment/runner.py", line 523, in <module>
    sys.exit(main())
  File "/src/experiment/runner.py", line 516, in main
    experiment_main()
  File "/src/experiment/runner.py", line 501, in experiment_main
    runner.conduct_trial()
  File "/src/experiment/runner.py", line 284, in conduct_trial
    self.do_sync(final_sync=True)
  File "/src/experiment/runner.py", line 357, in do_sync
    logs.error('Failed to sync cycle: %d.', self.cycle)
  File "/src/common/logs.py", line 201, in error
    log(logger, logging.ERROR, message, *args, extras=extras)
  File "/src/common/retry.py", line 81, in _wrapper
    result = func(*args, **kwargs)
  File "/src/common/logs.py", line 161, in log
    logging.log(severity, message, *args)
Message: 'Failed to sync cycle: %d. Extras: {\'traceback\': \'Traceback (most recent call last):\\n  File "/src/experiment/runner.py", line 374, in record_stats\\n    stats_json_str = fuzzer_module_get_stats(output_corpus,\\n  File "/src/fuzzers/afl/fuzzer.py", line 51, in get_stats\\n    with open(stats_file) as file_handle:\\nFileNotFoundError: [Errno 2] No such file or directory: \\\'/out/corpus/fuzzer_stats\\\'\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File "/src/experiment/runner.py", line 353, in do_sync\\n    self.record_stats()\\n  File "/src/experiment/runner.py", line 378, in record_stats\\n    logs.error(\\\'Call to %d failed.\\\', fuzzer_module_get_stats)\\n  File "/src/common/logs.py", line 198, in error\\n    message % args)\\nTypeError: %d format: a number is required, not function\\n\'}'
Arguments: (1,)
`

**Comment by jonathanmetzman** [comment]
Thanks for this issue.
I'm a bit busy for the next few days, possibly until next sunday (July 18) so I don't know how soon I'll be able to look into this. But I will examine this when I get a chance.

**Comment by jonathanmetzman** [comment]
Sorry for the delay. Thank you for reporting this. I've figured out how to fix your problem and fixed a few of FuzzBench's own issues along the way. tl;dr you picked a nonexistent fuzz target (`fuzz_target`) you should pick one that exists like `h2o-fuzzer-http3`.
I'll close this issue for now. Please let me know if I've resolved the issue and if not please reopen.

There are 3 issues here:
1. The most important of these is a mistake you made in your command: `PYTHONPATH=. python3 benchmarks/oss_fuzz_benchmark_integration.py -p h2o -f fuzz_target -c 49dc92128490d34aba00dfbde440979b9633ba14 -d 2021-07-06T06:35:23+09:00`
Specifically, in `-f fuzz_target`.
`fuzz_target` is not a fuzz target here.
That's why `ERROR:root:Fuzz target binary not found`
If I fix this, by picking `h2o-fuzzer-http3`, for example, and rerun the command, everything works:
`PYTHONPATH=. python3 benchmarks/oss_fuzz_benchmark_integration.py -p h2o -f h2o-fuzzer-http3 -c 49dc92128490d34aba00dfbde440979b9633ba14 -d 2021-07-06T06:35:23+09:00`
make run-afl-h2o-h2o-fuzzer-http3
2. The second issue is that there is nothing to warn users when they are picking a nonexistent fuzz-target.
This is hard to fix without introducing too much complexity. For now I've added a log message to recommend running
make test-run-$BENCHMARK (although that wouldn't have helped you since you did test the integration.

1. The last issue is FuzzBench's and is related to logging. 
This issue was only triggered by the mistake you made that I mentioned above.
I've fixed that here: https://github.com/google/fuzzbench/pull/1216
This issue made it harder to figure out what was wrong because it caused a bunch of extra stacktraces to print.
