### ISSUE TITLE
libpcap issue with AFL-based fuzzers

### ISSUE THREAD

**Issue by thuanpv** [google/fuzzbench#136]
It seems that libpcap benchmark has some issue with AFL-based fuzzer. I run some tests locally and see that AFL and AFLSmart output something strange as copied below -- queue cycle number keeps increasing rapidly while there are no new test cases

```
[*] Entering queue cycle 19946.
[*] Fuzzing test case #0 (3 total, 0 uniq crashes found)...
[*] Fuzzing test case #1 (3 total, 0 uniq crashes found)...
[*] Fuzzing test case #2 (3 total, 0 uniq crashes found)...
[*] Entering queue cycle 19947.
[*] Fuzzing test case #0 (3 total, 0 uniq crashes found)...
[*] Fuzzing test case #1 (3 total, 0 uniq crashes found)...
[*] Fuzzing test case #2 (3 total, 0 uniq crashes found)...
[*] Entering queue cycle 19948.
[*] Fuzzing test case #0 (3 total, 0 uniq crashes found)...
[*] Fuzzing test case #1 (3 total, 0 uniq crashes found)...
[*] Fuzzing test case #2 (3 total, 0 uniq crashes found)...
```

Meanwhile, libfuzzer works well. Its output is copied below

```
NEW_FUNC: 0x5924e0  (/out/fuzz_both+0x5924e0)
NEW_FUNC: 0x592550  (/out/fuzz_both+0x592550)
#117110: cov: 330 ft: 466 corp: 59 exec/s 21364 oom/timeout/crash: 0/0/0 time: 5s job: 2 dft_time: 0
#189290: cov: 378 ft: 560 corp: 123 exec/s 18045 oom/timeout/crash: 0/0/0 time: 9s job: 3 dft_time: 0
#288835: cov: 397 ft: 615 corp: 161 exec/s 19909 oom/timeout/crash: 0/0/0 time: 14s job: 4 dft_time: 0
```

**Comment by vanhauser-thc** [comment]
As far as I have understood the libpcap benchmark there is no corpus. So several issues hit afl-like fuzzers:
 - roadblocks like CMP() will be very difficult to pass as no corpus file solves this
 - deterministic fuzzing slows down path discovery without a corpus

in aflplusplus we solve this by activating laf-intel (and have expanded on this a lot compared to the previous initial implementation by laf-intel, eg. expanding to float compares).
-d also helps on these targets (but -d is not good if there is a nice corpus ... so we need target specific command line options for fuzzers).

**Comment by thuanpv** [comment]
Thanks @vanhauser-thc. It makes sense to me. According to this https://github.com/google/oss-fuzz/blob/master/projects/libpcap/build.sh there is a seed corpus. And when I check the running docker container I see one seed as well. But I did not check how good the seed is.

**Comment by jonathanmetzman** [comment]
This target is somewhat weird and it wouldn't have been my top choice, but I think we should leave it since it reveals interesting differences in fuzzers (at least until the differences are better understood).

I agree with @vanhauser-thc about the likely reasons. In the experiment we are currently running (results should come this weekend or early next week), we are trying one version of vanilla AFL without `-d` and one version with, this might reveal some differences.

@thuanpv I'm pretty sure this target does not have a seed corpus. Other fuzzers in the project do. For a seed corpus to be used it has to be named `$FUZZ_TARGET_NAME_seed_corpus.zip`.
There is no `fuzz_both_seed_corpus.zip`.

**Comment by jonathanmetzman** [comment]
> -d also helps on these targets (but -d is not good if there is a nice corpus ... so we need target specific command line options for fuzzers).

One of the advantages of using Python code for running the fuzzer is that this sort of logic can be easily implemented. We currently write a testcase containing 'hi' if there is no seed corpus in the afl fuzzer.py everyone imports from. I could change it so that we also use `-d` in that case.
But I'm still not sure how much we should be doing this since the purpose of the project is to benchmark fuzzers, not the wrapper code that runs them. I'd rather this kind of logic was implemented in the fuzzers themselves (I realize it's hard for AFL since AFL wants to tell users not to run without a seed in the only way people would notice, by refusing to run).

**Comment by thuanpv** [comment]
I agree with you all so I close this issue.
