### ISSUE TITLE
compile targets with -O2 or -O3?

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#138]
aflplusplus and fastcgs compile targets with -O3 (changed by individual devs, one of them me) and I noticed that all other projects are set to -O2.

This changes the target CFGs, execution speeds, etc. so this should either be -O2 or -O3 for all (to be fair comparisons) IMHO.

Is there a reason that -O2 was initially chosen?

**Comment by jonathanmetzman** [comment]
Thanks I noticed this was an issue too. I've since changed every fuzzer to use -O3 (in #126).

>Is there a reason that -O2 was initially chosen?

Not really. For fuzzing in general I'm not sure what the best is (in OSS-Fuzz/ClusterFuzz we use -O1 but I think this is based on the (I think) incorrect theory that higher levels reduce the number of program edges).

But in FuzzBench it probably doesn't matter as long as it is consistent. I think I will look into making -O3 the default so fuzzer maintainers don't need to worry about it.
