### ISSUE TITLE
Local experiment only use one CPU core

### ISSUE THREAD

**Issue by sleicasper** [google/fuzzbench#1398]
I have a virtual machine that have 50 CPU cores, but all experimental programs are running on the first CPU core.

**Comment by jonathanmetzman** [comment]
Each trial is only supposed to use one core. Unless you give more detail it sounds like this WAI.

**Comment by apach301** [comment]
> I have a virtual machine that have 50 CPU cores, but all experimental programs are running on the first CPU core.

Hi! Did you specified `-rc` and `-mc` options when launching run_experiment.py? They are useful for local experiments as they allow to specify how much cores will be used for the experiment. Number of running cores is fuzzers * benchmarks * trials. It is strange, that in your case only one CPU core is used, maybe the problem is how it works under virtual machine?

**Comment by jonathanmetzman** [comment]
Maybe https://github.com/google/fuzzbench/pull/1399 solves your problem

**Comment by sleicasper** [comment]
After using latest commit from repo, it seems that it solves the problem.
