### ISSUE TITLE
Understanding differences between reports

### ISSUE THREAD

**Issue by wideglide** [google/fuzzbench#160]
I don't understand the differences in coverage achieved between different report dates.  Specifically, certain targets have a significant change in the coverage achieved by the top 5 fuzzers.

For instance, when comparing 2020-03-19 and 2020-03-16:
- curl changes from ~6250 to ~5400 edges covered
- woff2 changes from ~2400 to ~1050 edges covered
- wpantund changes from ~9100 to ~4100 edges covered

Other targets maintain the same relative number of edges covered.  I didn't see changes in the way the targets were compiled that would account for this kind of difference.   What am I missing that would cause these kind of differences?

**Comment by jonathanmetzman** [comment]
I'm looking into this.

>2020-3016

Sorry, is this a typo? do you mean 2020-03-16-fastcgs?

**Comment by wideglide** [comment]
yes, sorry both 2020-03-16 and 2020-03-11 have similar numbers, but 2020-03-19 changed

**Comment by jonathanmetzman** [comment]
On march 19th I committed [this change](https://github.com/google/fuzzbench/commit/0982a9f5dfc1dd75be46bda6d0def61e2b21c76e) which admittedly is not named correctly.

The change uses consistent optimization levels across fuzzers and gets rid of ASAN from them as well. This includes the "coverage" fuzzer which is what we use to measure the edges covered.

I think this is the reason for the change.
Sorry if this is causing you trouble in using our results.

This issue highlights a problem I'm working to solve.
Reports should have info on what code changed since the last report. This is similar to what is asked for in https://github.com/google/fuzzbench/issues/94. I think it would be important to have info on what changed in fuzzbench itself, not just the fuzzers. I might start with that since it is easier to solve.

**Comment by jonathanmetzman** [comment]
I confirmed that the change was landed before the experiment started. Here you can see that O3 is used and ASAN is not:
http://commondatastorage.googleapis.com/fuzzbench-data/2020-03-19/input/src/fuzzers/coverage/fuzzer.py

**Comment by wideglide** [comment]
ah, that makes sense.  The O0 to O3 change likely made a bigger difference for some programs.

**Comment by wideglide** [comment]
thanks for looking into this!
