### ISSUE TITLE
Should local docker run restrict cpu to 1 to match FuzzBench prod environment ?

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#176]
See also
https://github.com/google/fuzzbench/issues/173#issuecomment-605283610

**Comment by jonathanmetzman** [comment]
I have to look into it but I think we attempt this somewhere, it might not be possible.

**Comment by lszekeres** [comment]
Yes, I think doing this would be a good idea. Setting `--cpus=1` might be sufficient.
https://docs.docker.com/config/containers/resource_constraints/#configure-the-default-cfs-scheduler

**Comment by jonathanmetzman** [comment]
Hmm...in production we do [--cpuset-cpus=0](https://github.com/google/fuzzbench/blob/master/experiment/scheduler.py#L251) I wonder if this isn't sufficient or wrong.

**Comment by lszekeres** [comment]
> Hmm...in production we do [--cpuset-cpus=0](https://github.com/google/fuzzbench/blob/master/experiment/scheduler.py#L251) I wonder if this isn't sufficient or wrong, because I think the same code path was taken when Honggfuzz is used in a local experiment and I think Honggfuzz still used multiple threads.

Threads are independent from the CPU usage: ie you can run multiple threads on a single CPU. (In our case multiple threads are okay as long as a fuzzer doesn't go over 100% cpu usage.)

I think the --cpuset-cpu=0 flag means "use only the first cpu of the machine". That's a no op on our single cpu production vms. For local runs I think what we want is "don't use more than one cpu", which should be the --cpus=1 flag. (Otherwise all docker runs would try to use the same cpu)

**Comment by jonathanmetzman** [comment]
Production and local experiments now use --cpus=1 thanks to #8, so fixing this means just changing the Makefile to do the same.
