### ISSUE TITLE
Run fuzzers in CI

### ISSUE THREAD

**Issue by andreafioraldi** [google/fuzzbench#211]
Recently Marc opened a PR to test the different power schedules https://github.com/google/fuzzbench/pull/206.

I tested it locally while adding cmplog and he added the flags for the schedules in a wrong way.
`flags = ['-p fast']` instead of `flags = ['-p', 'fast']`

This prevented afl++ to start using make run-afplusplus-target.

In the PR is see that all Travis checks were passed but this is clearly a bug IMO.

**Comment by andreafioraldi** [comment]
I added the fix in the aflplusplus fork of fuzzbench, now it is in the cmplog PR https://github.com/google/fuzzbench/pull/210 (sorry ofc I can't open 2 PRs)

**Comment by jonathanmetzman** [comment]
I think CI isn't working 100% now but mainly because of false positives (i.e. spurious failures) not false negatives.

> Recently Marc opened a PR to test the different power schedules #206.
> 
> I tested it locally while adding cmplog and he added the flags for the schedules in a wrong way.
> `flags = ['-p fast']` instead of `flags = ['-p', 'fast']`
> 
> This prevented afl++ to start using make run-afplusplus-target.

We don't use make run-... in CI only make build-... though we definitely should do a quick run.
I'll mark this as an enhancement and we can implement this when we get a chance.
