### ISSUE TITLE
Error out when running out of GCP keys

### ISSUE THREAD

**Issue by mboehme** [google/fuzzbench#223]
I've been running a couple of experiments in the GCP setup and suddenly it stopped working. The script `experiment/run_experiment.py` terminates the SSH connection complaining that the dispatcher-container exited with status 1 while the dispatcher instance continues to run. Nothing comes up in the Error Console and the data bucket only holds the input folder.

Running the docker container manually on the instance it turned out that `gcloud` complains `RESOURCE_EXHAUSTED: Maximum number of keys on account reached.`

My workaround is removing a couple of keys from the service account. Go to the `IAM & Admin` page, select `Service accounts` and remove a recently created key. Can keys be reused? Otherwise, can the docs specify how to increase the key quota?

**Comment by inferno-chromium** [comment]
Keys get deleted when experiment finishes. Otherwise they stay. Even if you lose ssh connection to dispatcher, it does not affect anything, it will continue to run and finish on time. ssh connection is just to give you update, we can even just exit it out (since logging is all in stackdriver anyway).
When keys gets exhausted, you need to delete keys from service account page.

**Comment by mboehme** [comment]
I see. I killed the dispatcher a couple of times. It probably didn't have time to clean up. Thanks!
