### ISSUE TITLE
AFLrustrust

### ISSUE THREAD

**Issue by domenukk** [google/fuzzbench#230]
I transpiled afl++ to rust using c2rust here: http://github.com/domenukk/aflrustrust
Somebody suggested testing the speed of it - but this may be a waste of fuzz time as it _should_ be almost identical to the original c version of afl++.
What do you think?

**Comment by jonathanmetzman** [comment]
Right now testing the speed of the fuzzer isn't so straightforward because FuzzBench doesn't do any stats collection from fuzzers. You could do it offline though by downloading the zips of the output directory we provide and reading the data from fuzzer stats.
We would be able to observe differences if the slower speed resulted in less coverage though.
Are there plans to switch to a rust implementation or is this just meant to be a fun project.

**Comment by domenukk** [comment]
It's a fun side-project. I'm fine with not testing it further.
However, as both implementations should find exactly the same paths (as they are conceptually the same), paths found in time x should be the raw-ish speed - given similar cpu and mem load during tests.

**Comment by jonathanmetzman** [comment]
I think a one off test of this is fine, continuous is probably not a great use of resources.
We're trying to fix some scaling issues right now so it isn't a great time to be adding fuzzers but I'll post here when we can accept aflrustrust.

**Comment by jonathanmetzman** [comment]
Actually, it may also be a good idea to wait until we can collect stats on executions per second to do this.

**Comment by jonathanmetzman** [comment]
Send a PR if you want to run this. We can test it in an AFL++ experiment.
