### ISSUE TITLE
Dispatcher doesn't generate report.

### ISSUE THREAD

**Issue by mboehme** [google/fuzzbench#296]
Running AFL against another AFL-variant. The runners and fuzzers on those work properly. `experiment_folders` exists in the data bucket and on the dispatcher. It contains the corpus and result folders with the expected stdout output. `measurement-folders` exists on the dispatcher and also shows that coverage has been measured. 

However, the `snapshot` table in the SQL database remains empty. The `experiment` table indicates the start of the experiment. The Error Reporting only shows `ValueError: Empty experiment data. Message: Error generating HTML report.` Stackdriver under Global doesn't show anything unusual, except `Error generating HTML report.` The environment variables `CLOUD_SQL_INSTANCE_CONNECTION_NAME` and `POSTGRES_PASSWORD` as well as the config in `config/experiment.yaml` on the dispatcher are set properly - but DB connection should be fine, since the experiment-table is successfully written to. `_DEFAULT_SNAPSHOT_SECONDS` in common/experiment_utils.py is set to `6 * 60  # Seconds` and the experiment is run for 1 hour with two fuzzers on two benchmarks.

Suggestions on how to debug this?

**Comment by mboehme** [comment]
Turns out the AFL-variant didn't run properly after all. Report is generated fine now.

**Comment by mboehme** [comment]
So, the dispatcher updated the `snapshot` table at 360 seconds (which is when I closed this Issue). Been running for 45 min now and there is no other update to the `snapshot` table 🤔

**Comment by mboehme** [comment]
In `experiment-folders`, I can find snapshots of the seed corpora taken at the specified 6 min interval. At each snapshot, I can find an increasing number of seeds in the respective corpus. So, fuzzing works properly. For some reason, Stackdriver ceases to report that the coverage-binary is executed. After the second measure cycle, there are no more "Sancov files" entries logged. In the third cycle, Stackdriver logs a few `Corpus not found for cycle: 3.` Then, I get a DEBUG-level log that `Executed command: "nice -n 5 python3 -u -c import fuzzer; fuzzer.fuzz('/out/seeds', '/out/corpus', '/out/fuzz_dtlsclient')" returned: -9.` From then onwards, I can only see the successful  `gsutil cp corpus-archives/corpus-archive-*.tar.gz`.

I'll roll back to a 15 minutes `_DEFAULT_SNAPSHOT_SECONDS` to see whether this is the problem.

**Comment by mboehme** [comment]
Ended up reverting  c791a0d43 and 506a5395c. I'm 30 minutes into a six hours experiment and the report is successfully re-generated in 6 minutes snapshot intervals (as specified).

**Comment by jonathanmetzman** [comment]
Sorry about this. I'm still trying to figure out what is wrong with the patch (it's almost definitely related to the unchanged-cycles change) but it seems to work fine when measuring an experiment that is already finished.

**Comment by jonathanmetzman** [comment]
I think I figured it out, in https://github.com/google/fuzzbench/commit/506a5395c6d48036c66a58aeb03cab25f31827fa I changed a call to gsutil.cat to gsutil.cp. Well the gsutil.cat invocation used parallel=False and the invocation of cp uses parallel=True by default. When parallel=True many times in parallel some of the gsutil processes hang. In the current setup even one thread hanging breaks measuring (this was necessary when we were using a giant rsync, now it is not). Short term I'm going to fix the invocation of cp to use parallel=False, longer term I'm going to fix by making parallel=False the default everywhere and making the measurer more robust to hangs.

I'm running three experiments right now. I'm going to restart the measurer with these changes, and probably do another experiment (with the new benchmarks) shortly, so that should be a good test of whether this works now.

Note that the measurer is able to be run as a standalone script so if there is ever a bug, it's possible to restart the measurer midway through an experiment without losing any previous work.

**Comment by jonathanmetzman** [comment]
Usually we do experiments more frequently so we probably would have caught this error ourselves. Apologies that you had to run into it.

**Comment by mboehme** [comment]
No worries. It's been quite interesting to debug a system that builds Docker images on a dedicated Docker image building online service, automatically uploads those images to a dedicated remote container registry, starts VMs with individual roles (dispatcher and runners) that just pull those images.

How can I run the measurer? Do I need to run it on the dispatcher, or can I run it locally as well?

**Comment by jonathanmetzman** [comment]
> Do I need to run it on the dispatcher, or can I run it locally as well?

I've successfully run it locally (though some benchmarks required some dependencies my machine didn't have so they didn't get measured).

I'll give some instructions on how I did it below, but there may be somethings about my local setup that your might not have so running it locally might not work out of the box (e.g. I have gsutil/gcloud installed, etc).

> How can I run the measurer?
Starting it from the middle might cause issues if it isn't from the same directory where it last hung (because the measurer keeps some state there). I generally just delete all the snapshots in the db and use a fresh directory to be safe.

1. Set POSTGRES_PASSWORD in the environment
2. Connect to the database using cloud_sql_proxy (as explained here: https://google.github.io/fuzzbench/running-your-own-experiment/setting-up-a-google-cloud-project/#set-up-the-database) (if youre on the dispatcher this might be running already).

3. I use the command below to run the measurer, you'll need to substitute your own values:
```FORCE_NOT_LOCAL=True CLOUD_PROJECT=fuzzbench CLOUD_EXPERIMENT_BUCKET=gs://fuzzbench-data EXPERIMENT=2020-05-01-aflplusplus-1 WORK=/tmp/work PYTHONPATH=. python src/experiment/measurer.py 86400```
`86400` is the amount of seconds I'm running the experiment for.

It should log to the google cloud interface even if you do this locally (that's what FORCE_NOT_LOCAL does.

Let me know if you have trouble with this.
