### ISSUE TITLE
Input formats of the supported benchmarks - Request for help

### ISSUE THREAD

**Issue by thuanpv** [google/fuzzbench#527]
Hi,

I have been trying to collect the input formats information of the supported benchmarks in FuzzBench. The information could be helpful for structure-aware fuzzers such as Libprotobuf-mutator (LPM), AFLSmart, Nautilus, and Superion. However, the information that I have collected so far, as shown in the following table, is not complete yet because I am not familiar with some benchmarks. It would be great if someone could help to update the table in the editable shared spreadsheet at https://docs.google.com/spreadsheets/d/1KBgiZrHLGKu2hsHIp6IMsbxjCrgYDC0aQVQyEU4Ql_c/edit?usp=sharing. 

Benchmark | Currently Supported (File) Formats | Reference/Notes
-- | -- | --
bloaty_fuzz_target | ELF, Mach-O, WebAssembly |  
curl_curl_fuzzer_http | ? | Supports network protocols
freetype2-2017 | TTF, OTF, WOFF |  
harfbuzz-1.3.2 | TTF, OTF, TTC | https://harfbuzz.github.io/ch01s03.html
jsoncpp_jsoncpp_fuzzer | JSON |  
lcms-2017-03-21 | ICC profile |  
libjpeg-turbo-07-2017 | JPEG |  
libpcap_fuzz_both | PCAP |  
libpng-1.2.56 | PNG |  
libxml2-v2.9.2 | XML |  
mbedtls_fuzz_dtlsclient | ? | Supports network protocols
openssl_x509 | ? |  
openthread-2019-12-23 | ? | Supports Thread networking protocol
php_php-fuzz-parser | PHP |  
proj4-2017-08-14 | ? |  
re2-2014-12-09 | ? | Regular expression library
sqlite3_ossfuzz | SQLITE, DB? |  
systemd_fuzz-link-parser | ? |  
vorbis-2017-12-11 | OGG |  
woff2-2016-05-06 | WOFF |  
zlib_zlib_uncompress_fuzzer | ? |  

This is related to Issue #471 

Thuan

**Comment by vanhauser-thc** [comment]
openssl: DER certificates
zlib: zlib compressed data
the others I dont know but would guess its their own specific protocol data.

**Comment by thuanpv** [comment]
Thanks @vanhauser-thc. I have updated the Google Spreadsheet accordingly.

**Comment by jonathanmetzman** [comment]
Thanks @thuanpv and @vanhauser-thc 
I'll see if I know/can figure out the formats of the other benchmarks.
We could also ask the developers of these targets to confirm what they do since the targets are from OSS-Fuzz.

**Comment by jonathanmetzman** [comment]
Curl: HTTP server responses. Seed files **[here](https://github.com/curl/curl-fuzzer/tree/master/corpora/curl_fuzzer_http).

Systemd: [Systemd (network) link files](https://www.freedesktop.org/software/systemd/man/systemd.link.html). The page describes it as an ini style text file. [Seeds](https://github.com/systemd/systemd/tree/master/test/fuzz/fuzz-link-parser)

re2: [2 bytes for options followed by a regular expression](https://github.com/google/fuzzbench/blob/master/benchmarks/re2-2014-12-09/target.cc). Looks like it matches itself which doesn't seem great (we might want to switch to taking a string to match on and a regex).
The options will make grammar aware fuzzing harder as I see one of them turns on posix style regexes (instead of perl I assume).

proj4: [This builds standard_fuzzer.cpp](https://github.com/google/fuzzbench/blob/master/benchmarks/proj4-2017-08-14/build.sh#L41). [Here is the current copy.](https://github.com/OSGeo/PROJ/blob/master/test/fuzzers/standard_fuzzer.cpp#L66).
It takes a format that looks somewhat custom but involves coordinates. There's probably more details on that [here](https://github.com/OSGeo/PROJ), but I'll try to get some lower hanging fruit for now.

zlib: zlib compressed files (see [fuzz target source code](https://github.com/google/oss-fuzz/blob/master/projects/zlib/zlib_uncompress_fuzzer.cc))

sqlite3: [Uses 3 (?) bytes for configuration](https://github.com/sqlite/sqlite/blob/master/test/ossfuzz.c#L132) followed by [SQL to execute](https://github.com/sqlite/sqlite/blob/master/test/ossfuzz.c#L183) (the rest of the data becomes zsql).

mbedtls: I had a hard time figuring out what this does from reading [the code](https://github.com/ARMmbed/mbedtls/blob/6abc20e0e3c89d790be355c922cf3c07cf0480c8/programs/fuzz/fuzz_dtlsclient.c#L92) but it gets set as the [`p_bio` field of an mbedtls_ssl_context struct ](https://github.com/ARMmbed/mbedtls/blob/a92e3def48c927f14eb84dadaebcdf9a382e29c9/include/mbedtls/ssl.h#L1178). The comment for this field says it is "context for I/O operations" (not very helpful :-(
The [seed file](https://github.com/ARMmbed/mbedtls/blob/a92e3def48c927f14eb84dadaebcdf9a382e29c9/programs/fuzz/corpuses/dtlsclient) isn't too helpful either, but I would strongly guess this is the data read by the client during a tls connection. There are some more hints provided by the implementations of some of the fuzzer-specific callbacks they pass to the API functions they are testing: https://github.com/ARMmbed/mbedtls/blob/6abc20e0e3c89d790be355c922cf3c07cf0480c8/programs/fuzz/common.c#L35

Probably worth asking about this one.

**Comment by jonathanmetzman** [comment]
Oh forgot openthread:
[It's using the ip6-send-fuzzer](https://github.com/google/fuzzbench/blob/master/benchmarks/openthread-2019-12-23/build.sh#L69) ([source code](https://github.com/openthread/openthread/blob/master/tests/fuzz/ip6_send.cpp)). It looks like it uses a byte for configuration and then the rest of the data gets passed to [otIp6Send](https://github.com/openthread/openthread/blob/master/tests/fuzz/ip6_send.cpp#L72). [The docs for that function](https://github.com/openthread/openthread/blob/master/include/openthread/ip6.h#L471) says "This function sends an IPv6 datagram via the Thread interface."  So I guess it is an IPv6 packet?

Once https://github.com/google/fuzzbench/pull/509 lands it should be easy for anyone to add OSS-Fuzz projects as benchmarks so if any of the benchmarks seem crappy, they can be replaced.

**Comment by inferno-chromium** [comment]
Reopen if needed - see https://google.github.io/fuzzbench/reference/benchmarks/
