### ISSUE TITLE
Local: Failed to build base image

### ISSUE THREAD

**Issue by jiradeto** [google/fuzzbench#620]
Git hash: a634c2f5d1c78af6ee1b0f6165bff951a600078d

When running with local mode, I was unable to start an experiment and got the following error:

```
Traceback (most recent call last):
  File "/work/src/experiment/dispatcher.py", line 184, in <module>
    sys.exit(main())
  File "/work/src/experiment/dispatcher.py", line 169, in main
    raise error
  File "/work/src/experiment/dispatcher.py", line 166, in main
    dispatcher_main()
  File "/work/src/experiment/dispatcher.py", line 126, in dispatcher_main
    experiment.num_trials, preemptible)
  File "/work/src/experiment/dispatcher.py", line 92, in build_images_for_trials
    builder.build_base_images()
  File "/work/src/experiment/build/builder.py", line 55, in build_base_images
    return buildlib.build_base_images()
  File "/work/src/experiment/build/local_build.py", line 38, in build_base_images
    return make(['base-runner', 'base-builder'])
  File "/work/src/experiment/build/local_build.py", line 33, in make
    return new_process.execute(command, cwd=utils.ROOT_DIR)
  File "/work/src/common/new_process.py", line 124, in execute
    raise subprocess.CalledProcessError(retcode, command)
subprocess.CalledProcessError: Command '['make', '-j', 'base-runner', 'base-builder']' returned non-zero exit status 2.
```

**Comment by jonathanmetzman** [comment]
I have a trivial fix for this and the other issue you experienced. But I assume you got past this error since the second one is deeper in the code right?

**Comment by jiradeto** [comment]
> Thanks!
> I have a trivial fix for this and the other issue you experienced. But I assume you got past this error since the first one you reported is deeper in the code right?

@jonathanmetzman Yes, just wanted to address this issue on the repo in case others experiencing the same problem can see.

**Comment by jonathanmetzman** [comment]
Thanks for that.
Fixed in https://github.com/google/fuzzbench/commit/c1b41402a090042e17bf123662aefb71780cb593

I'm glad your using the local experiments but it isn't documented because it isn't really supported. So if you run into issues you may need to fix them yourself but we'd be happy to accept patches or provide guidance.
I can think of 2 sharp edges you might run into:
1. The scheduler has code for starting trials locally but not for stopping trials. You may need to add that code unless youre fine stopping the trials using docker commands manually
2. There is no resource control so if you ask for an experiment with too many trials for your machine, fuzzbench will schedule them all at once. This shouldn't be a problem as long as you are running tiny experiments.

Also, keep in mind we can run experiments for you with the fuzzbench service.
