### ISSUE TITLE
Add link to fuzzbench-data artifacts in fuzzbench report.

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#641]

**Comment by jonathanmetzman** [comment]
We should probably store it in the db when we create an experiment.
Maybe we should have a JSON field that stores the entire config?

**Comment by jonathanmetzman** [comment]
cc @Shadoom7

**Comment by Shadoom7** [comment]
May I ask what is this link specifically? The link to the html reports or to the experiment folder in data bucket?

**Comment by jonathanmetzman** [comment]
Actually I think this won't involve you at all. SOrry for the confusion. My thought was if we stored the data bucket in the experiment entity in the db we could use it to solve this issue and use it to derive links to reports. But since you will link to reports I guess the sollutions will be different.

**Comment by Shadoom7** [comment]
Got you!

**Comment by jonathanmetzman** [comment]
The other thing worth mentioning, it might be worth putting one of those index files in there to making browsing easier. Otherwise the XML rendered will link to the thousands of files.

**Comment by inferno-chromium** [comment]
Duplicate of https://github.com/google/fuzzbench/issues/161
