### ISSUE TITLE
LLVMgold in default installation

### ISSUE THREAD

**Issue by vanhauser-thc** [google/fuzzbench#646]
A very new llvm is in the build images (good!) -> llvm12.
However LLVMgold is not installed. And as the llvm packages are not in apt I can install it during build time.
can you please add it to the base build system? (it would be in the llvm-12-dev package)
thanks.

**Comment by inferno-chromium** [comment]
I think this is complicated since base build image comes from OSS-Fuzz and some of the benchmarks use a particular version of that image, e.g. https://github.com/google/fuzzbench/blob/master/benchmarks/bloaty_fuzz_target/Dockerfile#L17

Did you mean to install it in the benchmark builder image here - https://github.com/google/fuzzbench/blob/master/docker/benchmark-builder/Dockerfile#L32. Better to build from source - https://llvm.org/docs/GoldPlugin.html#how-to-build-it

**Comment by vanhauser-thc** [comment]
> I think this is complicated since base build image comes from OSS-Fuzz and some of the benchmarks use a particular version of that image, e.g. https://github.com/google/fuzzbench/blob/master/benchmarks/bloaty_fuzz_target/Dockerfile#L17

I see ... is it then possible to have the repo link where the built llvm packges come from that are installed?
then I could do apt install llvm-12-dev, which is currently not possible, as there is no repo for it.

> Did you mean to install it in the benchmark builder image here - https://github.com/google/fuzzbench/blob/master/docker/benchmark-builder/Dockerfile#L32. Better to build from source - https://llvm.org/docs/GoldPlugin.html#how-to-build-it

no, I  need it in the builder image.
gold is there (it is default everywhere for some years now) what is missing is the LLVMgold.so plugin, which needs to be built in the llvm-project tree. and then I would need to use the same version that the installed version is, and this is moving from time to time ... so building LLVMgold.so myself is a useful option.

**Comment by inferno-chromium** [comment]
> > I think this is complicated since base build image comes from OSS-Fuzz and some of the benchmarks use a particular version of that image, e.g. https://github.com/google/fuzzbench/blob/master/benchmarks/bloaty_fuzz_target/Dockerfile#L17
> 
> I see ... is it then possible to have the repo link where the built llvm packges come from that are installed?
> then I could do apt install llvm-12-dev, which is currently not possible, as there is no repo for it.
> 
> > Did you mean to install it in the benchmark builder image here - https://github.com/google/fuzzbench/blob/master/docker/benchmark-builder/Dockerfile#L32. Better to build from source - https://llvm.org/docs/GoldPlugin.html#how-to-build-it
> 
> no, I need it in the builder image.
> gold is there (it is default everywhere for some years now) what is missing is the LLVMgold.so plugin, which needs to be built in the llvm-project tree. and then I would need to use the same version that the installed version is, and this is moving from time to time ... so building LLVMgold.so myself is a useful option.

So, i was discussing this with @jonathanmetzman sometime back which is we should have latest llvm image for all benchmarks. If that is the case, then this is super simple. We can add LLVMGold to https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/checkout_build_install_llvm.sh and then it magically shows up everywhere. I think he mentioned some issue with crash benchmarkinng where people needed older image, but maybe it is still ok.
@vanhauser-thc - you want to start with submitting a patch to install llvmGold in that script [https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/checkout_build_install_llvm.sh] as /usr/bin/ld.gold (not replacing the default, but available in /usr/bin).

**Comment by jonathanmetzman** [comment]
>So, i was discussing this with @jonathanmetzman sometime back which is we should have latest llvm image for all benchmarks.

I don't think we will change this for at least a few weeks though if we decide to change it at all. So it may be best to implement an AFL++-specific solution.

>I think he mentioned some issue with crash benchmarkinng where people needed older image, but maybe it is still ok.

Yes for crash benchmarking, we want to build versions of projects that are potentially a few years old. Pinning the oss-fuzz-builder image we inherit from makes the process for adding these benchmarks smoother. The build will just work instead of potentially breaking on a newer clang version.

>I see ... is it then possible to have the repo link where the built llvm packges come from that are installed?

Do you mean the source code we use to build the rest of LLVM?
That gets deleted earlier on during the OSS-Fuzz build process so I think it would be a bit difficult.
I think building lld.gold wouldn't be too hard though. Just clone LLVM and use `LLVM_ENABLE_PROJETS=lld` with cmake and then build the project. You can use the shell script Abhishek linked to (https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/checkout_build_install_llvm.sh) as a rough guide though some steps won't be necessary like the MSAN stuff or the two stage build.

**Comment by vanhauser-thc** [comment]
done. the change is very different to what you expect though ;)
