### ISSUE TITLE
Support fuzzer configurations for different build time flags 

### ISSUE THREAD

**Issue by andreafioraldi** [google/fuzzbench#73]
I've written a new fuzzer.py for AFL++ that supports build time configurations.

https://github.com/andreafioraldi/fuzzbench/blob/master/fuzzers/aflplusplus/fuzzer.py

`build()` needs an env variable `BUILD_MODES` that can be a comma-separated combination of qemu,cmplog,laf

Fuzzers flags are configured like for libfuzzer, with the `ADDITIONAL_FLAGS` env var.

**Comment by jonathanmetzman** [comment]
On build time flags:
I have to think about how this can be supported. I'd like to do it to be consistent with the runtime flags, but it seems like it might require some complexity to support.
Basically, if we support this, then the image at gcr.io/fuzzbench/builders/aflplusplus/freetype2-2017 won't be the right one for all aflplusplus freetype builds, we would need to include the build flags in the tag somehow.

Do you think the runtime flags feature is useful or do you prefer new integrations (e.g. making an `aflplusplus-qemu` directory in `fuzzers/`)?
If runtime flags are useful, do you think they are useful enough to keep if build time variants required a new integration?

On your integration itself:
Nice! I really like the qemu variant. I want to do binary instrumentation benchmarking as well.

I'll probably hoist that `restore_directory` `contextmanager` to `fuzzers/fuzzer_utils.py` so that it can be reused instead of copied (it can be reused currently by importing from qsym but it'd be cleaner to import from utils).

**Comment by jonathanmetzman** [comment]
> On build time flags:
> I have to think about how this can be supported. I'd like to do it to be consistent with the runtime flags, but it seems like it might require some complexity to support.
> Basically, if we support this, then the image at gcr.io/fuzzbench/builders/aflplusplus/freetype2-2017 won't be the right one for all aflplusplus freetype builds, we would need to include the build flags in the tag somehow.

After discussing this with some team members, I think I'm going to try to support this.

**Comment by andreafioraldi** [comment]
> Do you think the runtime flags feature is useful or do you prefer new integrations (e.g. making an aflplusplus-qemu directory in fuzzers/)?

For me it's the same, there will be 4 aflplusplus in fuzzers/ in that case:
aflplusplus, aflplusplus-lafintel, aflplusplus-cmplog, aflplusplus-qemu

**Comment by inferno-chromium** [comment]
Ideally we want to enable things in default configuration if possible and unless we know they are too much detrimental to regular fuzzing (most common usecase). Curious if lafintel and cmplog work together and do they slow down significantly to not enable in default case ?

**Comment by andreafioraldi** [comment]
> Curious if lafintel and cmplog work together and do they slow down significantly to not enable in default case ?

laf-intel cannot be default because it introduces collisions (3x more edges in the program) and so it's better to have it optional.

CmpLog requires a lot of memory mapped (256 MB circa, not all used so the kernel does not really maps all the pages) and is very useful when you don't have many initial seeds and you application has a lot of comparisons. But, if you have a good corpus and a good dictionary, you don't need it, it is decremental.

**Comment by inferno-chromium** [comment]
Thanks @andreafioraldi , configurations makes sense then.

**Comment by jonathanmetzman** [comment]
We've decided not to do anything special for configuration on the FuzzBench side. Variants can import anything they want from other fuzzer.py files and use them however they'd like. I think this solution is by far the simplest for both Fuzzbench to implement since it's no additional work to support and for users (who don't need to learn to use some configuration system in addition to fuzzer.py and Docker to integrated fuzzers.
