### ISSUE TITLE
make clear-cache: Delete only Fuzzbench images and containers

### ISSUE THREAD

**Issue by mboehme** [google/fuzzbench#784]
Currently, `make clear-cache` runs 
```
docker stop $(docker ps -a -q) 2>/dev/null ; \
docker rm -vf $(docker ps -a -q) 2>/dev/null ; \
docker rmi -f $(docker images -a -q) 2>/dev/null ; \
docker volume rm $(docker volume ls -q) 2>/dev/null ; true
```
which also removes all unrelated images and containers.

**Comment by inferno-chromium** [comment]
yes we should fix that.

**Comment by jonathanmetzman** [comment]
We should fix it by getting rid of `make clear-cache` I don't think there is a use case for it really.

**Comment by mboehme** [comment]
On my cloud machine, I don't have a lot of disk space. This is what I usually run to clean out Fuzzbench containers and containers before testing a fuzzer-benchmark configuration.
```
docker rm $(docker ps -qa --no-trunc --filter "status=exited")
docker rmi -f $(docker images | grep -e gcr -e none | sed 's/  */ /g' | cut -d" " -f3 | sort | uniq)
```

**Comment by jonathanmetzman** [comment]
Thanks, this is definitely more precise but is still overlybroad for some users (e.g. if you also use OSS-Fuzz, it will delete those images). We could do gcr.io/fuzzbench but that might break when we start having local experiments.
To some extent I think we should suggest this in documentation but not provide it since it's more docker specific than project-specific.

**Comment by mboehme** [comment]
Agree. This works for me.
