### ISSUE TITLE
Presubmit script in CI not linting new files correctly

### ISSUE THREAD

**Issue by jonathanmetzman** [google/fuzzbench#95]
At least in CI it seems to ignore new files.
See for example https://github.com/google/fuzzbench/runs/499383388 where it didn't error on a file that was added but not formatted correctly.

**Comment by jonathanmetzman** [comment]
Actually, looks like modifying old files isn't properly checked either https://github.com/google/fuzzbench/pull/96/checks?check_run_id=501269051

**Comment by inferno-chromium** [comment]
yes i noticed that too.

**Comment by ammaraskar** [comment]
The `get_changed_files` function https://github.com/google/fuzzbench/blob/a96560010456c066e5f9e18de53dbb9334d005ed/presubmit.py#L261-L273

won't work on CIs because the `FETCH_HEAD` is the commit being pull requested. Maybe it should just be run on all files in the CI unless this is prohibitively expensive?

**Comment by jonathanmetzman** [comment]
Thanks Ammar, I'll look into the methods you've proposed.
I think https://github.com/google/fuzzbench/pull/97 should work though

**Comment by jonathanmetzman** [comment]
Should be fixed by #97
