### ISSUE TITLE
Builds hangs with aflplusplus_optimal aflplusplus on some new bug based benchmarks

### ISSUE THREAD

**Issue by inferno-chromium** [google/fuzzbench#965]
Build failures: [('aflplusplus', 'php_php-fuzz-execute'), ('aflplusplus_optimal', 'php_php-fuzz-execute'), ('aflplusplus_optimal', 'arrow_parquet-arrow-fuzz'), ('lafintel', 'arrow_parquet-arrow-fuzz')]

and also newly added php_php-fuzz-parser i think

**Comment by inferno-chromium** [comment]
@Vaush @vanhauser-thc fyi

**Comment by Vaush** [comment]
I can't reproduce the failure. I've run make test-run-aflplusplus-php_php-fuzz-execute and it works for me locally, while make test-run-afl-php_php-fuzz-execute actually throws an error about a file not found (not sure what the problem is, will check).
Is there any difference between the command I run and the command run during the production build?

**Comment by inferno-chromium** [comment]
Can you try aflplusplus_optimal with php and arrow, that was definitely failing.

**Comment by vanhauser-thc** [comment]
with aflplusplus it compiles, but it takes 4 hours to do so on my system. _optimal (which by default uses LTO unless configured otherwise) will increase that exponantially.

**Comment by inferno-chromium** [comment]
> with aflplusplus it compiles, but it takes 4 hours to do so on my system. _optimal (which by default uses LTO unless configured otherwise) will increase that exponantially.

yes 4 hr will be too much, should we disable them, i prefer to change any config settings that makes them work, and then show them in bug based benchmarking [for those benchmarks].

**Comment by Vaush** [comment]
Right now optimal is still running, but I removed the LTO option for php already. I will start another run and time it precisely, but I can see right now that the build section is taking ages on aflplusplus_optimal, although I can't understand why exactly.
I'd say as long as it is aflplusplus and variations, and not afl itself, we could decide to just blacklist it. After all, if it can't even build the benchmark that should be a point against it, what do you think?

**Comment by inferno-chromium** [comment]
> Right now optimal is still running, but I removed the LTO option for php already. I will start another run and time it precisely, but I can see right now that the build section is taking ages on aflplusplus_optimal, although I can't understand why exactly.
> I'd say as long as it is aflplusplus and variations, and not afl itself, we could decide to just blacklist it. After all, if it can't even build the benchmark that should be a point against it, what do you think?

yes will blacklist, i wanted to make sure there were no other workarounds or incorrect setup.

**Comment by Vaush** [comment]
I mean, I can keep thinking about it, but I don't have any leads on why honestly. It just hangs on one of the make instructions and takes a lot of time to complete, there is no errors nor warnings

**Comment by inferno-chromium** [comment]
disabled in https://github.com/google/fuzzbench/pull/972

**Comment by vanhauser-thc** [comment]
@inferno-chromium 
I analyzed the issues, and it is this: "-fsanitize=array-bounds,bool,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,null,object-size,return,returns-nonnull-attribute,shift,signed-integer-overflow,unsigned-integer-overflow,unreachable,vla-bound,vptr" - this increases the compile time x15 - and that is with 8 cores.
I think the reason is that the instrumentation is added in the last step when the target has increased complexity ...
